- hosts: localhost
  connection: local
  vars:
    proxy_host: "192.168.64.1"
    proxy_port: "1087"
    proxy: "http://192.168.64.1:1087"
  environment:
    http_proxy: "{{proxy}}"
    HTTP_PROXY: "{{proxy}}"
    https_proxy: "{{proxy}}"
    HTTPS_PROXY: "{{proxy}}"
    all_proxy: "{{proxy}}"
    ALL_PROXY: "{{proxy}}"
  tasks:
    - import_tasks: ../tasks/package.yml
    - import_tasks: ../tasks/git.yml
    - import_tasks: ../tasks/volta.yml
    - import_tasks: ../tasks/starship.yml
    - import_tasks: ../tasks/oh-my-zsh.yml
    - import_tasks: ../tasks/tmux.yml
    - import_tasks: ../tasks/docker.yml
    - import_tasks: ../tasks/ssh.yml
    - import_tasks: ../tasks/dotfiles.yml
    # 可选安装
    # - import_tasks: ../tasks/homebrew.yml

