- hosts: localhost
  connection: local
  vars:
    proxy_host: "192.168.64.1"
    proxy_port: "1087"
    proxy: "http://192.168.64.1:1087"
  environment:
    http_proxy: "{{proxy}}"
    HTTP_PROXY: "{{proxy}}"
    https_proxy: "{{proxy}}"
    HTTPS_PROXY: "{{proxy}}"
    all_proxy: "{{proxy}}"
    ALL_PROXY: "{{proxy}}"
  tasks:
    - import_tasks: ../tasks/homebrew.yml

