- name: Install git
  become: true
  package:
    name:
      - git
      - git-extras
      - socat
    state: present

- name: Copy .gitconfig
  copy:
    src: config/.gitconfig
    dest: ~/.gitconfig

- name: git ssh proxy config
  copy:
    dest: ~/.ssh/config.d/github
    content: |-
      Host github.com
         HostName github.com
         User git
         ProxyCommand socat - PROXY:{{proxy_host}}:%h:%p,proxyport={{proxy_port}}
         # for socks5 proxy
         # ProxyCommand nc -v -x 127.0.0.1:7890 %h %p
         # for windows
         # ProxyCommand connect -S 127.0.0.1:7890 -a none %h %p
