# https://github.com/Homebrew/install
# 默认安装会中断的, 需要设置 NO_INTERACTION=1
# 安装过程比较长, 走 github 仓库大约 30min, 国内镜像大约 8m
# 可添加输出重定向 >> uninstall_homebrew.log

# - name: Uninstall Homebrew
#   shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)" -- -f
#   ignore_errors: true

# 测试连通性
- name: nslookup homebrew repo
  shell: nslookup github.com
  register: nslookup

- debug:
    var: nslookup.stdout

- name: Install Homebrew
  shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" >> /tmp/install_homebrew.log
  # environment:
  #   HOMEBREW_BREW_GIT_REMOTE: "https://mirrors.ustc.edu.cn/brew.git"
  #   HOMEBREW_CORE_GIT_REMOTE: "https://mirrors.ustc.edu.cn/homebrew-core.git"
  args:
    creates: /home/linuxbrew/.linuxbrew/bin/brew

# 还原 brew git 仓库
- name: reset brew repo
  shell: git -C "/home/linuxbrew/.linuxbrew/Homebrew" remote set-url origin https://github.com/Homebrew/brew

# 还原 homebrew-core git 仓库
- name: reset homebrew-core repo
  shell: git -C "/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/homebrew/homebrew-core" remote set-url origin https://github.com/Homebrew/homebrew-core

# 检测 brew doctor 是否有异常
- name: run brew doctor
  shell: /home/linuxbrew/.linuxbrew/bin/brew doctor
  register: doctor
  ignore_errors: true

- debug:
    var: doctor.stdout

- name: Install neofetch
  homebrew:
    name: neofetch
    path: /home/linuxbrew/.linuxbrew/bin
    state: present

- name: install lsd
  homebrew:
    name: lsd
    path: /home/linuxbrew/.linuxbrew/bin
    state: present

- name: tap mcfly
  homebrew_tap:
    name: cantino/mcfly
    path: /home/linuxbrew/.linuxbrew/bin

- name: install mcfly
  homebrew:
    name: cantino/mcfly/mcfly
    path: /home/linuxbrew/.linuxbrew/bin
    state: present


# - name: install broot
#   homebrew:
#     name: broot
#     path: /home/linuxbrew/.linuxbrew/bin
#     state: present

