# 安装过程设置免交互

- name: Install zsh
  become: true
  package:
    name:
      - zsh
    state: present

# 为当前用户, 设置默认 shell
- name: Change default shell to zsh
  shell: sudo chsh -s "$(which zsh)" "$(whoami)"


#If absent, directories will be recursively deleted, and files or symlinks will be unlinked.
- name: Ensures .oh-my-zsh dir absent
  file:
    path: ~/.oh-my-zsh
    state: absent

- name: Install ohmyzsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended

- name: Copy .zshrc
  copy:
    src: config/.zshrc
    dest: ~/.zshrc
