- name: Ensures ~/.ssh dir exists
  file:
    path: ~/.ssh
    state: directory

- name: Copy .ssh/config
  copy:
    src: config/.ssh/config
    dest: ~/.ssh/config

- name: Ensures ~/.ssh/config.d dir exists
  file:
    path: ~/.ssh/config.d
    state: directory

- name: write .ssh/config.d/github
  copy:
    dest: ~/.ssh/config.d/github
    content: |-
      Host github.com
         HostName github.com
         User git
         ProxyCommand socat - PROXY:{{proxy_host}}:%h:%p,proxyport={{proxy_port}}
         # for socks5 proxy
         # ProxyCommand nc -v -x 127.0.0.1:7890 %h %p
         # for windows
         # ProxyCommand connect -S 127.0.0.1:7890 -a none %h %p

- name: Copy github-leohxj_rsa
  copy:
    src: config/.ssh/github-leohxj_rsa
    dest: ~/.ssh/github-leohxj_rsa

- name: Copy coding-leohxj_rsa
  copy:
    src: config/.ssh/coding-leohxj_rsa
    dest: ~/.ssh/coding-leohxj_rsa

- name: Copy tencent-sh_rsa
  copy:
    src: config/.ssh/tencent-sh_rsa
    dest: ~/.ssh/tencent-sh_rsa

# 更新权限
- name: Copy tencent-sh_rsa
  shell: chmod 600 ~/.ssh/*_rsa

