# 安装 volta, 需要中断操作
- name: Install Volta JavaScript Tool Manager.
  shell: "curl https://get.volta.sh | bash"
  args:
    creates: "{{ ansible_env.HOME }}/.volta"

# 安装 node
- name: Install default node version.
  shell: "{{ ansible_env.HOME }}/.volta/bin/volta install node"
  args:
    creates: "{{ ansible_env.HOME }}/.volta/bin/node"


# 安装 yarn
- name: Install default node version.
  shell: "{{ ansible_env.HOME }}/.volta/bin/volta install yarn"
  args:
    creates: "{{ ansible_env.HOME }}/.volta/bin/yarn"

# 安装 yarn
- name: Install default node version.
  shell: "{{ ansible_env.HOME }}/.volta/bin/volta install pnpm"
  args:
    creates: "{{ ansible_env.HOME }}/.volta/bin/pnpm"

# 安装 rimraf
- name: Install global npm packages rimraf
  shell: "{{ ansible_env.HOME }}/.volta/bin/volta install rimraf"
  args:
    creates: "{{ ansible_env.HOME }}/.volta/bin/rimraf"

# 安装 serve
- name: Install global npm packages serve
  shell: "{{ ansible_env.HOME }}/.volta/bin/volta install serve"
  args:
    creates: "{{ ansible_env.HOME }}/.volta/bin/serve"

# 列出已安装的模块
- name: List installed npm packages.
  shell: "{{ ansible_env.HOME }}/.volta/bin/volta list"
