# 安装 volta, 需要中断操作
- name: Install Volta JavaScript Tool Manager.
  shell: "curl https://get.volta.sh | bash"
  args:
    creates: "{{ ansible_env.HOME }}/.volta"

# 安装 node, 需要强制安装, 因为 volta 默认自带了个 bin
- name: Volta Install node
  shell: "volta install node"
  environment:
    PATH: "{{ ansible_env.HOME }}/.volta/bin:{{ansible_env.PATH}}"

# 安装 yarn, 需要强制安装, 因为 volta 默认自带了个 bin
- name: Volta Install yarn
  shell: "volta install yarn"
  environment:
    PATH: "{{ ansible_env.HOME }}/.volta/bin:{{ansible_env.PATH}}"

# 安装 pnpm
- name: Volta Install pnpm
  shell: "volta install pnpm"
  environment:
    PATH: "{{ ansible_env.HOME }}/.volta/bin:{{ansible_env.PATH}}"
  args:
    creates: "{{ ansible_env.HOME }}/.volta/bin/pnpm"

# 安装 rimraf
- name: Volta Install rimraf
  shell: "volta install rimraf"
  environment:
    PATH: "{{ ansible_env.HOME }}/.volta/bin:{{ansible_env.PATH}}"
  args:
    creates: "{{ ansible_env.HOME }}/.volta/bin/rimraf"

# 安装 serve
- name: Volta Install serve
  shell: "volta install serve"
  environment:
    PATH: "{{ ansible_env.HOME }}/.volta/bin:{{ansible_env.PATH}}"
  args:
    creates: "{{ ansible_env.HOME }}/.volta/bin/serve"
  retries: 3
  ignore_errors: true

# 列出已安装的模块
- name: Volta list installed npm packages.
  shell: "volta list"
  environment:
    PATH: "{{ ansible_env.HOME }}/.volta/bin:{{ansible_env.PATH}}"

